// ABOUTME: Sidebar configuration for Docusaurus docs site.
// ABOUTME: Auto-generates sidebar from filesystem using sidebar_position frontmatter.

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
